- hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create a Storage Account
      azure_rm_storageaccount:
        resource_group: jenkins
        location: eastus
        name: successb74b73
        kind: StorageV2
        access_tier: Hot
        account_type: Standard_LRS
